Fix #284
R2NorthstarTools/FlightCore pull request #562
Opened 2023-09-13 01:41 UTC by Ombrezz

`check_northstar_running()` only returns true if Northstar wasn't launched with the `-dedicated` flag, untested on Windows.

2023-09-13 10:55 UTC, GeckoEidechse reviewed
Many thanks for the PR <3

I enabled CI and it failed [clippy check](https://doc.rust-lang.org/stable/clippy/usage.html).

The fix should be [explained in CI logs](https://github.com/R2NorthstarTools/FlightCore/actions/runs/6166903897/job/16749200116#step:7:815).

If you have any questions, LMK ^^

2023-09-14 21:13 UTC, GeckoEidechse commented on src-tauri/src/util.rs
>  /// Checks if Northstar process is running
Would also update the comment

```suggestion
/// Checks if Northstar process is running (ignores dedicated server)
```

2023-09-14 21:14 UTC, GeckoEidechse requested changes
So in quick testing on Windows, this cause non-dedicated-Northstar to be detected as running.

Both when starting first a dedi server and then client, and when only starting a client.

2023-09-14 22:26 UTC, Ombrezz commented
The `sysinfo` crate [suggests](https://docs.rs/sysinfo/latest/sysinfo/index.html#usage) `refresh_all()` on a new `System` struct to get all the information up to date, maybe that will fix it?

2023-09-18 11:16 UTC, GeckoEidechse commented
Nope, looks like it still has the same issue... :/

![image](https://github.com/R2NorthstarTools/FlightCore/assets/40122905/ccae4b22-b0cc-4b77-8186-6aa3f764f1a5)

Did it work for you locally?

2023-09-18 19:55 UTC, Ombrezz commented
Works fine for me on Linux, could you run a quick test to see what `sysinfo` returns for the `name()`, `exe()`, and `cmd()` functions on the Northstar and/or TF2 processes on Windows?

2024-09-29 23:16 UTC, Alystrasz requested changes

2024-09-29 23:16 UTC, Alystrasz commented on src-tauri/src/util.rs
> +        if (process.name().ends_with("Titanfall2.exe") || process.name().ends_with("Northstar.exe"))
Related to https://github.com/R2NorthstarTools/FlightCore/pull/562#issuecomment-1723204223 I think, process name was changed in this PR while it shouldn't have been modified:
```suggestion
        if (process.name().ends_with("Titanfall2.exe") || process.name().ends_with("NorthstarLauncher.exe"))
```

2026-07-15 00:07 UTC, Alystrasz commented
Closing as stale.

2026-07-15 00:07 UTC, closed without merging