feat: Rebuild enabledmods.json if value not found
R2NorthstarTools/FlightCore pull request #69
Opened 2022-11-25 14:08 UTC by GeckoEidechse

When toggling a mod on enabled mods that is not present in `enabledmods.json` we would previously just error out. Now we rebuild the `enabledmods.json` file in a Northstar compatible format and then toggle the mod in question.

This means no more
![image](https://user-images.githubusercontent.com/40122905/204002177-c6a9eb78-68cd-4740-82fc-d8e33e6ba906.png)

:D

2022-11-27 20:19 UTC, Alystrasz requested changes
Tested on Windows, works fine when a mod key is missing.
This however doesn't work when:
* `enabledmods.json` file does not exist
* `enabledmods.json` does not contain a valid JSON document (is empty, for instance)

2022-11-27 20:19 UTC, Alystrasz commented on src-tauri/src/mod_management/mod.rs
> +    println!("{}", serde_json::to_string_pretty(&obj).unwrap());
Unnecessary print here

2022-11-27 20:57 UTC, GeckoEidechse commented on src-tauri/src/mod_management/mod.rs
> +    println!("{}", serde_json::to_string_pretty(&obj).unwrap());
Removed with 5f2c333b4cf88f40bc02c8bf091ad9d579f74b0a

2022-11-27 20:58 UTC, GeckoEidechse commented
> This however doesn't work when:
> 
> * `enabledmods.json` file does not exist
> * `enabledmods.json` does not contain a valid JSON document (is empty, for instance)

Didn't even think about that, good catch :D

Fixed in acdf8107bd6c5824ee6eab6bfd123a9a07be5c71

2022-11-28 06:08 UTC, Alystrasz approved these changes
Tested successfully on Linux with above-mentioned use-cases.

2022-11-28 06:08 UTC, merged